name: Automated UI tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default:
        type: choice
        options:
          - chrome-without-auth
          - chrome-with-auth
          - firefox-without-auth
          - firefox-with-auth

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  download-history:
    runs-on: ubuntu-latest
    name: Download Allure report history
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: >
          $ARTIFACT_ID=$(curl -L 
          -H "Accept: application/vnd.github+json"
          -H "X-GitHub-Api-Version: 2022-11-28"
          "https://api.github.com/repos/shmurge/onlineStore/actions/artifacts?name=allure_report" 
          | python3 -c "import sys, json; print(json.load(sys.stdin)['artifacts'][0]['id']);") 
          &&
          echo $ARTIFACT_ID
          &&
          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/shmurge/onlineStore/actions/artifacts/$ARTIFACT_ID/zip 
          -o artifacts.zip
        continue-on-error: true
      - run: mkdir allure_report && unzip artifacts.zip -d allure_report
        continue-on-error: true
      - name: Download allure history
        uses: actions/upload-artifact@v4
        with:
          name: Allure report
          path:
            allure_report
          retention-days: 1

  test-run:
    name: Test run
    runs-on: ubuntu-latest
    needs: download-history

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Chrome
        if: "github.event.inputs.deployment_target == 'chrome-without-auth' || 
        github.event.inputs.deployment_target == 'chrome-with-auth'"
        run: sudo apt-get install google-chrome-stable
      - name: Install Firefox
        if: "github.event.inputs.deployment_target == 'firefox-without-auth' ||
        github.event.inputs.deployment_target == 'firefox-with-auth'"
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
      - name: chrome-without-auth
        if: "github.event.inputs.deployment_target == 'chrome-without-auth'"
        run: pytest -v -s --tb=line --reruns=3 --headless --alluredir allure_report
        continue-on-error: true
      - name: chrome-with-auth
        if: "github.event.inputs.deployment_target == 'chrome-with-auth'"
        run: pytest -v -s --tb=line --reruns=3 --headless --login -m=may_be_login --alluredir allure_report
        continue-on-error: true
      - name: firefox-without-auth
        if: "github.event.inputs.deployment_target == 'firefox-without-auth'"
        run: pytest -v -s --tb=line --reruns=3 --headless --browser=firefox --github_actions --alluredir allure_report
        continue-on-error: true
      - name: firefox-with-auth
        if: "github.event.inputs.deployment_target == 'firefox-with-auth'"
        run: > 
          pytest -v -s --tb=line --reruns=3 --headless --browser=firefox 
          --github_actions --login -m=may_be_login --alluredir allure_report
        continue-on-error: true
      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure_report
          path:
            allure_report
          retention-days: 1

  generate-allure-report:
    name: Generate Allure report
    runs-on: ubuntu-latest
    needs: test-run

    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: > 
          sudo wget https://github.com/allure-framework/allure2/releases/download/2.32.0/allure-2.32.0.tgz 
          && 
          sudo tar -zxvf allure-2.32.0.tgz -C /opt/ && sudo ln -s /opt/allure-2.32.0/bin/allure /usr/bin/allure
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
      - run: allure generate -c allure_report -o _site
      - name: Upload generated Allure report
        uses: actions/upload-artifact@v4
        with:
          name: _site
          path:
            _site
          retention-days: 1

  publish-allure-report:
    name: Publication allure-report
    runs-on: ubuntu-latest
    needs: generate-allure-report
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
      - name: Deploy to Github pages
        uses: actions/deploy-pages@v4
