name: Automated tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default:
        type: choice
        options:
          - chrome-without-auth
          - chrome-with-auth
          - firefox-without-auth
          - firefox-with-auth

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Chrome
        if: "github.event.inputs.deployment_target == 'chrome-without-auth' || 
        github.event.inputs.deployment_target == 'chrome-with-auth'"
        run: sudo apt-get install google-chrome-stable
      - name: Install Firefox
        if: "github.event.inputs.deployment_target == 'firefox-without-auth' ||
        github.event.inputs.deployment_target == 'firefox-with-auth'"
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: chrome-without-auth
        if: "github.event.inputs.deployment_target == 'chrome-without-auth'"
        run: pytest -v -s --tb=line --reruns=3 --headless
      - name: chrome-with-auth
        if: "github.event.inputs.deployment_target == 'chrome-with-auth'"
        run: pytest -v -s --tb=line --reruns=3 --headless --login -m=may_be_login
      - name: firefox-without-auth
        if: "github.event.inputs.deployment_target == 'firefox-without-auth'"
        run: pytest -v -s --tb=line --reruns=3 --headless --browser=firefox
      - name: firefox-with-auth
        if: "github.event.inputs.deployment_target == 'firefox-with-auth'"
        run: pytest -v -s --tb=line --reruns=3 --headless --browser=firefox --login -m=may_be_login

